name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ilfarodellostudio
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Announce Build
      run: echo "🚀 Starting Project Build..."

    - name: Build Project 
      env:
        DB_URL: jdbc:mysql://127.0.0.1:3306/ilfarodellostudio
        DB_USER: root
        DB_PWD: root
      run: ./mvnw clean package 

    - name: Announce Tests
      run: echo "✅ Build and Tests Successful!"
